### ISSUE TITLE
cimg/ruby:3.1.3 LoadError: cannot load such file -- 3.1/ffi_c

### ISSUE THREAD

**Issue by schinery** [CircleCI-Public/cimg-ruby#100]
I'm updating an app from Ruby 3.1.2 to 3.1.3 and I'm getting the following error when running the CI tests using the new cimg/ruby image.

```sh
#!/bin/bash -eo pipefail
bundle exec rails db:setup
rails aborted!

LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap/engine.rb:4:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:61:in `register_rails_engine'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:11:in `load!'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:75:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `each'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `block in require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `each'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler.rb:186:in `require'
/home/circleci/my-app/config/application.rb:9:in `<main>'
/home/circleci/my-app/Rakefile:6:in `require_relative'
/home/circleci/my-app/Rakefile:6:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: cannot load such file -- 3.1/ffi_c
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:3:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap/engine.rb:4:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:61:in `register_rails_engine'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:11:in `load!'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.2.3/lib/bootstrap.rb:75:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `each'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `block in require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `each'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `require'
/home/circleci/.rubygems/gems/bundler-2.3.26/lib/bundler.rb:186:in `require'
/home/circleci/my-app/config/application.rb:9:in `<main>'
/home/circleci/my-app/Rakefile:6:in `require_relative'
/home/circleci/my-app/Rakefile:6:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/circleci/my-app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

Exited with code exit status 1
CircleCI received exit code 1
```

This works as expected using the Ruby 3.1.2 image so is it the case that we’d need to install the ffi lib manually now?

**Comment by mattbrictson** [comment]
If you are caching your `vendor/bundle` directory (e.g. via the Ruby orb and `ruby/install-deps`), you may need to change your cache key to manually bust the cache. I also ran into an issue where `vendor/bundle` generated in a Ruby 3.1.2 build did not work on Ruby 3.1.3 and gave a similar error.

**Comment by schinery** [comment]
Thanks @mattbrictson it was indeed the cache, once I'd bust that everything installed and is working as expected.

**Comment by deepakmahakale** [comment]
I faced the same issue today after upgrading to 3.1.3 changing the cache key for bundle worked 👍
