### ISSUE TITLE
Missing psych.so for the "yaml" gem.

### ISSUE THREAD

**Issue by jcoyne** [CircleCI-Public/cimg-ruby#67]
When I use `cimg/ruby:2.7-browsers` I run into this error:

```
Gemfile.lock is bundled with bundler version 2.2.15
Installing bundler 2.2.15
Fetching bundler-2.2.15.gem
Successfully installed bundler-2.2.15
1 gem installed
The following gems are missing
 * racc (1.5.2)
 * nio4r (2.5.7)
 * websocket-driver (0.7.5)
 * bcrypt (3.1.16)
 * bindex (0.8.1)
 * msgpack (1.4.2)
 * bootsnap (1.7.5)
 * rbtree (0.4.4)
 * byebug (11.1.3)
 * commonmarker (0.22.0)
 * psych (3.3.2)
 * ffi (1.15.3)
 * pg (1.2.3)
 * puma (4.3.8)
Install missing gems with `bundle install`
/usr/local/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: libruby.so.2.7: cannot open shared object file: No such file or directory - /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/psych-3.3.2/lib/psych.so
Traceback (most recent call last):
	48: from /home/circleci/.rubygems/bin/bundle:23:in `<main>'
	47: from /home/circleci/.rubygems/bin/bundle:23:in `load'
	46: from /home/circleci/.rubygems/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	45: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	44: from /home/circleci/.rubygems/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	43: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
	42: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	41: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
	40: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	39: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	38: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	37: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/cli.rb:258:in `install'
	36: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/settings.rb:115:in `temporary'
	35: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/cli.rb:259:in `block in install'
	34: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/cli/install.rb:64:in `run'
	33: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/installer.rb:24:in `install'
	32: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/installer.rb:72:in `run'
	31: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/process_lock.rb:9:in `lock'
	30: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/process_lock.rb:9:in `open'
	29: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/process_lock.rb:12:in `block in lock'
	28: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/installer.rb:83:in `block in run'
	27: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/installer.rb:291:in `resolve_if_needed'
	26: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/definition.rb:173:in `resolve_remotely!'
	25: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/definition.rb:185:in `specs'
	24: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `materialize'
	23: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `map!'
	22: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/spec_set.rb:86:in `block in materialize'
	21: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/lazy_specification.rb:72:in `__materialize__'
	20: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:104:in `specs'
	19: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:406:in `remote_specs'
	18: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/index.rb:9:in `build'
	17: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:407:in `block in remote_specs'
	16: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:271:in `fetchers'
	15: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:271:in `map'
	14: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:273:in `block in fetchers'
	13: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/source/rubygems.rb:273:in `new'
	12: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/fetcher.rb:88:in `initialize'
	11: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/fetcher.rb:246:in `connection'
	10: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/rubygems_integration.rb:114:in `configuration'
	 9: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/rubygems_integration.rb:114:in `require_relative'
	 8: from /home/circleci/.rubygems/gems/bundler-2.2.15/lib/bundler/psyched_yaml.rb:12:in `<top (required)>'
	 7: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 6: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 5: from /usr/local/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'
	 4: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 3: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 2: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/psych-3.3.2/lib/psych.rb:13:in `<top (required)>'
	 1: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': libruby.so.2.7: cannot open shared object file: No such file or directory - /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/psych-3.3.2/lib/psych.so (LoadError)

Exited with code exit status 1

```

**Comment by jcoyne** [comment]
This was a case caused by using a dirty cache, using a new cache key fixed it.
