### ISSUE TITLE
Unable to load rails database when using postgres and "db/structure.sql"

### ISSUE THREAD

**Issue by jcoyne** [CircleCI-Public/cimg-ruby#68]
This tries to use `psql`, which is not in the docker image.

When I have a rails env that uses postgresql and is configured to use `config.active_record.schema_format = :sql`, then when I try to run `rake db:setup` (which calls `db:schema:load`) the following error occurs:

```
Created database 'h2_test'
rails aborted!
failed to execute:
psql --set ON_ERROR_STOP=1 --quiet --no-psqlrc --file /home/circleci/project/db/structure.sql h2_test

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.

/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:111:in `run_cmd'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:86:in `structure_load'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:314:in `structure_load'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:328:in `load_schema'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:435:in `block in load_schema_current'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:503:in `each'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:502:in `each'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/tasks/database_tasks.rb:434:in `load_schema_current'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4/lib/active_record/railties/databases.rake:462:in `block (3 levels) in <main>'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
```

**Comment by jcoyne** [comment]
The fix I used is to add a step:
```
      - run:
          name: Install psql
          command: sudo apt update && sudo apt install -y postgresql-client
 ```
 
 but I wonder if this shouldn't be installed by default.

**Comment by felicianotech** [comment]
Installing `postgresql-client` via Apt-get is the recommended solution for images that currently exists. Starting with the next Ruby release/image, `psql` will be pre-installed. For those interested, `psql` is pre-installed in newer versions of the CircleCI base image.
