### ISSUE TITLE
Can't find the ImageMagick library or one of the dependent libraries

### ISSUE THREAD

**Issue by thibhosman** [CircleCI-Public/cimg-ruby#76]
Hi there,

We just migrate to the new syntax of the docker images and at first we got the same error as here https://github.com/CircleCI-Public/cimg-ruby/issues/69 but resolved it by changing the cache version (or so it seems).

Now it fails because of missing image magick libraries:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/circleci/repo/vendor/bundle/ruby/2.7.0/gems/rmagick-4.2.2/ext/RMagick
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r
./siteconf20211208-184-1lyu133.rb extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found


ERROR: Can't install RMagick 4.2.2.
Can't find the ImageMagick library or one of the dependent libraries.
Check the mkmf.log file for more detailed information.


*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/circleci/repo/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/rmagick-4.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/circleci/repo/vendor/bundle/ruby/2.7.0/gems/rmagick-4.2.2 for inspection.
Results logged to
/home/circleci/repo/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/rmagick-4.2.2/gem_make.out

  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:93:in `run'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
  /usr/local/lib/ruby/2.7.0/tempfile.rb:291:in `open'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:159:in
`build_extension'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:193:in `block in
build_extensions'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:190:in `each'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:190:in
`build_extensions'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:845:in
`build_extensions'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/source/rubygems.rb:192:in
`install'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/installer/gem_installer.rb:54:in
`install'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/worker.rb:62:in
`apply_func'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/worker.rb:57:in
`block in process_queue'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/worker.rb:54:in
`loop'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/worker.rb:54:in
`process_queue'
/home/circleci/.rubygems/gems/bundler-2.2.26/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing rmagick (4.2.2), and Bundler cannot
continue.

In Gemfile:
  rmagick

Exited with code exit status 5
CircleCI received exit code 5
```

Should we install image magick as a dependency? Would it be cached?
Thank you.

**Comment by BytesGuy** [comment]
Hi, you will need to install the `libmagickcore-dev` package to get this to work. This appears to add about 70MB to the image in my testing building locally, so I am unsure if this is something we would add to images moving forward - deferring to @felicianotech for a second opinion

**Comment by felicianotech** [comment]
We only have three upvotes here on BytesGuy's comment on using `libmagickcore-dev`. For now, we're not going to pre-install it. We can reconsider this issue if a significant amount of people come back with this request.

For anyone reading, here's how you can install it during your build:

```bash
sudo apt-get update && sudo apt-get install -y libmagickcore-dev
```
